"""empty message

Revision ID: 82aafe1a146b
Revises: 
Create Date: 2019-06-24 22:20:09.063776

"""
from alembic import op
import sqlalchemy as sa
from db import sqlalchemy_jsonfield


# revision identifiers, used by Alembic.
revision = '82aafe1a146b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('marketplace_offer_id', sa.String(length=64), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('marketplace_date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_config', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('marketplace_offer_id'),
    sa.UniqueConstraint('server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    # ### end Alembic commands ###
